### ISSUE TITLE
Next button but a "no next slide" error

### ISSUE THREAD

**Issue by dan-jensen** [harishuw/jFormslider#1]
Hi, great plugin!  Just wanted to let you know that if any of the <li> elements contains a list with <li> items, the plugin fails.  The plugin renders a "Next" button on the last slide, and when you click on that button there are 3 console errors: 2x "Sorry!! There is no next slide" and 1x "Uncaught TypeError: Cannot read property 'hasAttr' of undefined."

The error can be replicated with this:

```
<form id="slider">
 <ul>
    <li>--form components--</li>
    <li>--form components--</li>
    <li>
        <ol><li>Some info!</li><li>More info!</li></ol>
    </li>
 </ul>
</form>
```

**Comment by harishuw** [comment]
Hi,

I have solved this issue.I tested with your code.
Please check it now and let me know if it is solved

**Comment by dan-jensen** [comment]
Fixed - it's working great now.  Nicely done, thank you!
